import {Telegraf,Markup} from "telegraf";import {message} from "telegraf/filters";import {randomBytes} from "node:crypto";import {config} from "./config.js";import {cb,urlBtn,box} from "./premium.js";import {initDb,ensureUser,getUser,getProducts,getProduct,stockCount,pool} from "./db/index.js";import {getState,setState,clearState} from "./state.js";
const bot=new Telegraf(config.token),isAdmin=(c:any)=>Number(c.from?.id)===config.adminId,id8=()=>randomBytes(4).toString("hex").toUpperCase();
async function home(c:any){const u=await getUser(c.from.id);return c.reply(box("✨ STORE DN CAR",`Welcome, ${c.from.first_name||"Customer"}\n\n👤 User ID: ${c.from.id}\n💰 Balance: $${Number(u?.balance||0).toFixed(2)}\n\n⚡ Fast • Secure • Premium Delivery`),Markup.inlineKeyboard([[cb("🛍 Shop","shop")],[cb("💰 Wallet","wallet"),cb("📦 My Orders","my_orders")],[cb("👤 Profile","profile"),cb("🎧 Support","support")],[urlBtn("📢 Channel",config.channelUrl),cb("❓ Help","help")]]))}
async function admin(c:any){return c.reply(box("👑 ADMIN PANEL","Choose an action:"),Markup.inlineKeyboard([[cb("📦 Tool Management","admin_tools")],[cb("📊 Stock Manage","admin_stock")],[cb("📢 Broadcast","admin_broadcast"),cb("❓ Help Manage","admin_help")],[cb("💳 Payment Settings","admin_payment")],[cb("🎟 Coupons","admin_coupons")],[cb("➕ Add Balance","admin_balance_add"),cb("➖ Remove Balance","admin_balance_remove")],[cb("💰 Check Balance","admin_balance_check")],[cb("🔎 Track Order ID","admin_track")],[cb("📊 Dashboard","admin_dashboard")]]))}
async function tools(c:any){const ps=await getProducts(),rows:any[]=[[cb("➕ Add Tool","admin_add_tool")],...ps.map((p:any)=>[cb(`📦 ${p.name}`,`admin_tool:${p.id}`)]),[cb("🔙 Back","admin_home")]];return c.reply(box("📦 TOOL MANAGEMENT","Select a tool:"),Markup.inlineKeyboard(rows))}
async function tool(c:any,id:string){const p=await getProduct(id);if(!p)return;const n=await stockCount(id);return c.reply(box("📦 TOOL CONTROL",`📦 ${p.name}\n💰 $${Number(p.price).toFixed(2)}\n🛡 ${p.warranty||"N/A"}\n📊 Stock: ${n}`),Markup.inlineKeyboard([[cb("✏️ Change Price",`field:price:${id}`),cb("🛡 Change Warranty",`field:warranty:${id}`)],[cb("📝 Change Description",`field:description:${id}`)],[cb("📌 Edit Note",`field:note:${id}`)],[cb("📬 Delivery Note",`field:delivery_note:${id}`)],[cb("📋 Delivery Template",`field:delivery_template:${id}`)],[cb(`${p.preorder_enabled?"🔴 Disable":"🟢 Enable"} Pre-Order`,`toggle:preorder_enabled:${id}`)],[cb("🔌 Link Supplier API",`supplier:${id}`)],[cb("🗑 Remove Tool",`remove_tool:${id}`)],[cb("🔙 Back","admin_tools")]]))}
bot.start(async c=>{await ensureUser(c.from.id,c.from.username,c.from.first_name);await home(c)});bot.command("admin",async c=>{if(isAdmin(c))await admin(c)});
bot.action("home",async c=>{await c.answerCbQuery();await home(c)});bot.action("shop",async c=>{await c.answerCbQuery();const ps=(await getProducts()).filter((p:any)=>p.active),rows:any[]=[];for(const p of ps){const n=await stockCount(p.id);rows.push([cb(`${n>0?"🟢":"🔴"} ${p.name}`,`product:${p.id}`)])}rows.push([cb("🔙 Back","home")]);await c.reply(box("🛍 SHOP",ps.length?"Choose a product:":"No products available."),Markup.inlineKeyboard(rows))});
bot.action(/^product:(.+)$/,async c=>{await c.answerCbQuery();const p=await getProduct(c.match[1]);if(!p)return;const n=await stockCount(p.id);await c.reply(box(`📦 ${p.name}`,`${p.description||"Premium digital product"}\n\n💰 Price: $${Number(p.price).toFixed(2)}\n📦 Stock: ${n}\n🛡 Warranty: ${p.warranty||"N/A"}${p.note?`\n\n📌 ${p.note}`:""}`),Markup.inlineKeyboard([[cb("🛒 Buy Now",`buy:${p.id}`)],[cb("🔙 Back","shop")]]))});
bot.action(/^buy:(.+)$/,async c=>{await c.answerCbQuery();setState(c.from.id,{step:"buy_qty",productId:c.match[1]});await c.reply("Send quantity:")});
bot.action("wallet",async c=>{await c.answerCbQuery();const u=await getUser(c.from.id),r=(await pool.query("SELECT COALESCE(SUM(total),0) t FROM orders WHERE user_id=$1",[c.from.id])).rows[0];await c.reply(box("💰 MY WALLET",`💵 Balance: $${Number(u?.balance||0).toFixed(2)}\n📦 Total Spent: $${Number(r?.t||0).toFixed(2)}`),Markup.inlineKeyboard([[cb("🔙 Back","home")]]))});
bot.action("profile",async c=>{await c.answerCbQuery();const u=await getUser(c.from.id),r=(await pool.query("SELECT COUNT(*)::int n FROM orders WHERE user_id=$1",[c.from.id])).rows[0];await c.reply(box("👤 PROFILE",`🆔 User ID: ${c.from.id}\n👤 Username: @${c.from.username||"N/A"}\n💰 Balance: $${Number(u?.balance||0).toFixed(2)}\n📦 Orders: ${r.n}`))});
bot.action("my_orders",async c=>{await c.answerCbQuery();const r=await pool.query("SELECT * FROM orders WHERE user_id=$1 ORDER BY created_at DESC LIMIT 10",[c.from.id]);await c.reply(box("📦 MY ORDERS",r.rows.length?r.rows.map((o:any)=>`✅ #${o.id} • ${o.product_name} x${o.quantity} • $${Number(o.total).toFixed(2)}`).join("\n"):"No orders yet."),Markup.inlineKeyboard([[cb("🔙 Back","home")]]))});
bot.action("support",async c=>{await c.answerCbQuery();await c.reply(box("🎧 SUPPORT",`Contact support: ${config.supportUsername}`),Markup.inlineKeyboard([[cb("🔙 Back","home")]]))});
bot.action("help",async c=>{await c.answerCbQuery();const r=await pool.query("SELECT * FROM help_items WHERE active=TRUE ORDER BY title");await c.reply(box("❓ HELP",r.rows.length?r.rows.map((x:any)=>`❓ ${x.title}\n${x.content}`).join("\n\n"):"No help articles yet."),Markup.inlineKeyboard([[cb("🔙 Back","home")]]))});
bot.action("admin_home",async c=>{if(isAdmin(c)){await c.answerCbQuery();await admin(c)}});bot.action("admin_tools",async c=>{if(isAdmin(c)){await c.answerCbQuery();await tools(c)}});bot.action(/^admin_tool:(.+)$/,async c=>{if(isAdmin(c)){await c.answerCbQuery();await tool(c,c.match[1])}});
bot.action("admin_add_tool",async c=>{if(isAdmin(c)){await c.answerCbQuery();setState(c.from.id,{step:"add_product_name"});await c.reply("Send tool name:")}});
bot.action(/^field:([^:]+):(.+)$/,async c=>{if(!isAdmin(c))return;await c.answerCbQuery();const f=c.match[1];if(!["price","warranty","description","note","delivery_note","delivery_template","name"].includes(f))return;setState(c.from.id,{step:"field",field:f,productId:c.match[2],numeric:f==="price"});await c.reply(`Send new ${f.replaceAll("_"," ")}:`)});
bot.action(/^toggle:(preorder_enabled):(.+)$/,async c=>{if(!isAdmin(c))return;await c.answerCbQuery();await pool.query(`UPDATE products SET ${c.match[1]}=NOT ${c.match[1]} WHERE id=$1`,[c.match[2]]);await tool(c,c.match[2])});bot.action(/^remove_tool:(.+)$/,async c=>{if(isAdmin(c)){await c.answerCbQuery();await pool.query("DELETE FROM products WHERE id=$1",[c.match[1]]);await c.reply("✅ Tool removed.");await tools(c)}});
bot.action("admin_stock",async c=>{if(!isAdmin(c))return;await c.answerCbQuery();const ps=await getProducts();await c.reply(box("📦 STOCK MANAGEMENT","Choose product:"),Markup.inlineKeyboard([...ps.map((p:any)=>[cb(`📦 ${p.name} (${p.id})`,`stock_add:${p.id}`)]),[cb("🔙 Back","admin_home")]]))});bot.action(/^stock_add:(.+)$/,async c=>{if(!isAdmin(c))return;await c.answerCbQuery();setState(c.from.id,{step:"add_stock",productId:c.match[1]});await c.reply("Paste stock now. Each non-empty line = one item.")});
bot.action("admin_dashboard",async c=>{if(!isAdmin(c))return;await c.answerCbQuery();const [u,p,o,s]=await Promise.all([pool.query("SELECT COUNT(*)::int n FROM users"),pool.query("SELECT COUNT(*)::int n FROM products"),pool.query("SELECT COUNT(*)::int n FROM orders"),pool.query("SELECT COALESCE(SUM(total),0) t FROM orders")]);await c.reply(box("📊 DASHBOARD",`👥 Users: ${u.rows[0].n}\n📦 Products: ${p.rows[0].n}\n🧾 Orders: ${o.rows[0].n}\n💰 Sales: $${Number(s.rows[0].t).toFixed(2)}`))});
for(const [a,k] of [["admin_balance_add","add"],["admin_balance_remove","remove"],["admin_balance_check","check"]] as const)bot.action(a,async c=>{if(!isAdmin(c))return;await c.answerCbQuery();setState(c.from.id,{step:"balance_user",action:k});await c.reply("Send Telegram User ID:")});
bot.action("admin_broadcast",async c=>{if(!isAdmin(c))return;await c.answerCbQuery();setState(c.from.id,{step:"broadcast"});await c.reply("Send broadcast text:")});bot.action("admin_payment",async c=>{if(!isAdmin(c))return;await c.answerCbQuery();await c.reply(box("💳 PAYMENT SETTINGS","Wallet / USDT / Binance Pay toggles are stored in database settings."))});bot.action("admin_coupons",async c=>{if(isAdmin(c)){await c.answerCbQuery();await c.reply(box("🎟 COUPONS","Coupon manager ready."))}});bot.action("admin_help",async c=>{if(isAdmin(c)){await c.answerCbQuery();await c.reply(box("❓ HELP MANAGE","Use the help creation flow in the source."))}});bot.action("admin_track",async c=>{if(isAdmin(c)){await c.answerCbQuery();setState(c.from.id,{step:"track_order"});await c.reply("Send Order ID:")}});
bot.on(message("text"),async c=>{await ensureUser(c.from.id,c.from.username,c.from.first_name);const uid=c.from.id,s=getState(uid),text=c.message.text.trim();if(!s)return;
if(s.step==="buy_qty"){const q=Number(text);if(!Number.isInteger(q)||q<1)return void c.reply("❌ Invalid quantity.");const db=await pool.connect();try{await db.query("BEGIN");const p=(await db.query("SELECT * FROM products WHERE id=$1 FOR UPDATE",[s.productId])).rows[0];const stock=await db.query("SELECT * FROM stock_items WHERE product_id=$1 AND sold=FALSE ORDER BY id FOR UPDATE LIMIT $2",[s.productId,q]);const u=(await db.query("SELECT * FROM users WHERE id=$1 FOR UPDATE",[uid])).rows[0],total=Number(p.price)*q;if(!p||stock.rows.length<q||Number(u.balance)<total)throw new Error(!p?"Product not found.":stock.rows.length<q?"Insufficient stock.":"Insufficient wallet balance.");const oid=id8(),vals=stock.rows.map((x:any)=>x.value);await db.query("UPDATE users SET balance=balance-$1 WHERE id=$2",[total,uid]);for(const x of stock.rows)await db.query("UPDATE stock_items SET sold=TRUE,sold_order_id=$1 WHERE id=$2",[oid,x.id]);await db.query("INSERT INTO orders(id,user_id,product_id,product_name,quantity,unit_price,total,delivery) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[oid,uid,p.id,p.name,q,p.price,total,vals.join("\n")]);await db.query("COMMIT");clearState(uid);await c.reply(box("✅ ORDER COMPLETED",`📦 ${p.name}\n🔢 Qty: ${q}\n🆔 #${oid}\n💰 Paid: $${total.toFixed(2)}\n\n${vals.map((v:string,i:number)=>`${i+1}. ${v}`).join("\n\n")}`))}catch(e:any){await db.query("ROLLBACK");await c.reply(`❌ ${e.message}`)}finally{db.release()}return}
if(!isAdmin(c))return;if(s.step==="add_product_name"){setState(uid,{step:"add_product_price",name:text});return void c.reply("Send price:")}if(s.step==="add_product_price"){const p=Number(text);if(!Number.isFinite(p)||p<0)return void c.reply("❌ Invalid price.");setState(uid,{step:"add_product_warranty",name:s.name,price:p});return void c.reply("Send warranty:")}if(s.step==="add_product_warranty"){setState(uid,{step:"add_product_desc",name:s.name,price:s.price,warranty:text});return void c.reply("Send description:")}if(s.step==="add_product_desc"){const id=id8();await pool.query("INSERT INTO products(id,name,price,warranty,description) VALUES($1,$2,$3,$4,$5)",[id,s.name,s.price,s.warranty,text]);clearState(uid);return void c.reply(`✅ Tool created. ID: ${id}`)}if(s.step==="field"){const v=s.numeric?Number(text):text;await pool.query(`UPDATE products SET ${s.field}=$1 WHERE id=$2`,[v,s.productId]);clearState(uid);return void c.reply("✅ Updated.")}if(s.step==="add_stock"){const items=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let a=0;for(const x of items){const r=await pool.query("INSERT INTO stock_items(product_id,value) VALUES($1,$2) ON CONFLICT(product_id,value) DO NOTHING RETURNING id",[s.productId,x]);if(r.rowCount)a++}clearState(uid);return void c.reply(`✅ Added ${a} stock item(s). Total: ${await stockCount(s.productId)}`)}if(s.step==="balance_user"){const id=Number(text);const u=await getUser(id);if(!u)return void c.reply("❌ User not found.");if(s.action==="check"){clearState(uid);return void c.reply(`💰 User ${id} balance: $${Number(u.balance).toFixed(2)}`)}setState(uid,{step:"balance_amount",action:s.action,userId:id});return void c.reply("Send amount:")}if(s.step==="balance_amount"){const a=Number(text);if(!Number.isFinite(a)||a<=0)return void c.reply("❌ Invalid amount.");const v=s.action==="add"?a:-a;await pool.query("UPDATE users SET balance=balance+$1 WHERE id=$2",[v,s.userId]);clearState(uid);return void c.reply("✅ Balance updated.")}if(s.step==="track_order"){const id=text.replace(/^#/,'').toUpperCase(),r=await pool.query("SELECT * FROM orders WHERE id=$1",[id]);clearState(uid);if(!r.rows[0])return void c.reply("❌ Order not found.");return void c.reply(box("🔎 ORDER DETAILS",JSON.stringify(r.rows[0],null,2)))}if(s.step==="broadcast"){clearState(uid);const us=await pool.query("SELECT id FROM users");let ok=0;for(const u of us.rows){try{await bot.telegram.sendMessage(u.id,text);ok++}catch{}}return void c.reply(`📢 Broadcast sent to ${ok}/${us.rows.length}`)}});
bot.catch(e=>console.error(e));await initDb();await bot.launch();console.log("STORE DN CAR bot started");process.once("SIGINT",()=>bot.stop("SIGINT"));process.once("SIGTERM",()=>bot.stop("SIGTERM"));