import {Telegraf,Markup} from "telegraf";import {message} from "telegraf/filters";import {randomBytes} from "node:crypto";
import {config} from "./config.js";import {cb,urlBtn,box,cleanPremiumIds} from "./premium.js";import {initDb,ensureUser,getUser,getProducts,getProduct,stockCount,pool} from "./db/index.js";import {getState,setState,clearState} from "./state.js";
const bot=new Telegraf(config.token);const hasAdminAccess=async(ctx:any)=>Number(ctx.from?.id)===config.adminId||Boolean((await pool.query("SELECT 1 FROM admins WHERE id=$1",[ctx.from?.id])).rowCount);const id8=()=>randomBytes(4).toString("hex").toUpperCase();
async function render(ctx:any,text:string,keyboard?:any){const safe=cleanPremiumIds(text);if(ctx.callbackQuery){try{await ctx.editMessageText(safe,keyboard);return}catch(error:any){if(String(error?.description||error?.message||"").includes("message is not modified"))return}}await ctx.reply(safe,keyboard);}
async function getSetting(key:string){return (await pool.query("SELECT value FROM settings WHERE key=$1",[key])).rows[0]?.value||"";}
async function setSetting(key:string,value:string){await pool.query("INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value",[key,value]);}
async function adminIds(){const r=await pool.query("SELECT id FROM admins");return [...new Set([config.adminId,...r.rows.map((x:any)=>Number(x.id))])];}
async function home(ctx:any){const u=await getUser(ctx.from.id);await render(ctx,box("✨ STORE DN CAR",`Welcome, ${ctx.from.first_name||"Customer"}\n\n👤 User ID: ${ctx.from.id}\n💰 Balance: $${Number(u?.balance||0).toFixed(2)}\n\n⚡ Fast • Secure • Premium Delivery`),Markup.inlineKeyboard([[cb("🛍 Shop","shop")],[cb("💰 Wallet","wallet"),cb("📦 My Orders","my_orders")],[cb("👤 Profile","profile"),cb("🎧 Support","support")],[urlBtn("📢 Channel",config.channelUrl),cb("❓ Help","help")]]));}
async function shop(ctx:any){const ps=(await getProducts()).filter((p:any)=>p.active);const rows:any[]=[];for(const p of ps){const n=await stockCount(p.id);rows.push([cb(`${n>0?"🟢":p.preorder_enabled?"🔵":"🔴"} ${p.name}`,`product:${p.id}`)])}rows.push([cb("🔙 Back","home")]);await render(ctx,box("🛍 SHOP",ps.length?"Choose a product:":"No products available."),Markup.inlineKeyboard(rows));}
async function product(ctx:any,id:string){const p=await getProduct(id);if(!p)return;const n=await stockCount(id);const status=n>0?"🟢 IN STOCK":p.preorder_enabled?"🔵 PRE-ORDER AVAILABLE":"🔴 OUT OF STOCK";const rows:any[]=[];if(n>0||p.preorder_enabled)rows.push([cb("🛒 Buy Now",`buy:${id}`)]);rows.push([cb("🔙 Back","shop")]);await render(ctx,box(`📦 ${p.name}`,`${p.description||"Premium digital product"}\n\n💰 Price: $${Number(p.price).toFixed(2)}\n📦 Stock: ${n}\n🛡 Warranty: ${p.warranty||"N/A"}\n\n${status}${p.note?`\n\n📌 ${p.note}`:""}`),Markup.inlineKeyboard(rows));}
function adminKeyboard(){return Markup.inlineKeyboard([[cb("📦 Tool Management","admin_tools")],[cb("📊 Stock Manage","admin_stock")],[cb("📢 Broadcast","admin_broadcast"),cb("❓ Help Manage","admin_help")],[cb("💳 Payment Settings","admin_payment"),cb("👑 Admins","admin_manage")],[cb("🎟 Coupons","admin_coupons")],[cb("➕ Add Balance","admin_balance_add"),cb("➖ Remove Balance","admin_balance_remove")],[cb("💰 Check Balance","admin_balance_check")],[cb("🔎 Track Order ID","admin_track")],[cb("📊 Dashboard","admin_dashboard")]]);}
async function admin(ctx:any){await render(ctx,box("👑 ADMIN HQ","Welcome boss 😎\nChoose your next move:"),adminKeyboard());}
async function tools(ctx:any){const ps=await getProducts();const rows:any[]=[[cb("➕ Add Tool","admin_add_tool")]];for(const p of ps)rows.push([cb(`📦 ${p.name}`,`admin_tool:${p.id}`)]);rows.push([cb("🔙 Back","admin_home")]);await render(ctx,box("📦 TOOL MANAGEMENT","Select a tool:"),Markup.inlineKeyboard(rows));}
async function tool(ctx:any,id:string){const p=await getProduct(id);if(!p)return;const n=await stockCount(id);await render(ctx,box("📦 TOOL CONTROL",`📦 ${p.name}\n💰 $${Number(p.price).toFixed(2)}\n🛡 ${p.warranty||"N/A"}\n📊 Stock: ${n}`),Markup.inlineKeyboard([[cb("✏️ Change Price",`field:price:${id}`),cb("🛡 Change Warranty",`field:warranty:${id}`)],[cb("📝 Change Description",`field:description:${id}`)],[cb("📌 Edit Note",`field:note:${id}`),cb("📌 Remove Note",`clear:note:${id}`)],[cb("📬 Delivery Note",`field:delivery_note:${id}`),cb("📬 Remove Dlv Note",`clear:delivery_note:${id}`)],[cb("📋 Set Delivery Template",`field:delivery_template:${id}`)],[cb("📦 Toggle Stock Status",`toggle:stock_enabled:${id}`)],[cb(`${p.client_mail_activation?"🔴 Disable":"🟢 Enable"} Client-Mail Activation`,`toggle:client_mail_activation:${id}`)],[cb(`${p.preorder_enabled?"🔴 Disable":"🟢 Enable"} Pre-Order`,`toggle:preorder_enabled:${id}`)],[cb("🔌 Link Supplier API",`supplier:${id}`)],[cb("➕ Add Sub Tool",`subtool_add:${id}`),cb("🧰 Manage Sub Tools",`subtool_manage:${id}`)],[cb("✏️ Rename Tool",`field:name:${id}`)],[cb("🗑 Remove Tool",`remove_tool:${id}`)],[cb("🔙 Back","admin_tools")]]));}
async function picker(ctx:any,prefix:string,title:string){const ps=await getProducts();const rows=ps.map((p:any)=>[cb(`📦 ${p.name}`,`${prefix}:${p.id}`)]);rows.push([cb("🔙 Back","admin_home")]);await render(ctx,box(title,"Select a tool:"),Markup.inlineKeyboard(rows));}

bot.start(async ctx=>{await ensureUser(ctx.from.id,ctx.from.username,ctx.from.first_name);await home(ctx)});bot.command("admin",async ctx=>{if(await hasAdminAccess(ctx))await admin(ctx)});
bot.action("home",async ctx=>{await ctx.answerCbQuery();await home(ctx)});bot.action("shop",async ctx=>{await ctx.answerCbQuery();await shop(ctx)});bot.action(/^product:(.+)$/,async ctx=>{await ctx.answerCbQuery();await product(ctx,ctx.match[1])});
bot.action("wallet",async ctx=>{await ctx.answerCbQuery();const u=await getUser(ctx.from.id);const s=(await pool.query("SELECT COALESCE(SUM(total),0) t FROM orders WHERE user_id=$1",[ctx.from.id])).rows[0];const d=(await pool.query("SELECT COUNT(*)::int n FROM deposits WHERE user_id=$1 AND status='pending'",[ctx.from.id])).rows[0];await render(ctx,box("💰 MY WALLET",`💵 Balance: $${Number(u?.balance||0).toFixed(2)}\n📦 Total Spent: $${Number(s?.t||0).toFixed(2)}\n⏳ Pending Deposits: ${d.n}\n\nReady to top up? 🚀`),Markup.inlineKeyboard([[cb("➕ Deposit Funds","deposit")],[cb("🔙 Back","home")]]))});
bot.action("profile",async ctx=>{await ctx.answerCbQuery();const u=await getUser(ctx.from.id);const o=(await pool.query("SELECT COUNT(*)::int n FROM orders WHERE user_id=$1",[ctx.from.id])).rows[0];await render(ctx,box("👤 PROFILE",`🆔 User ID: ${ctx.from.id}\n👤 Username: @${ctx.from.username||"N/A"}\n💰 Balance: $${Number(u?.balance||0).toFixed(2)}\n📦 Orders: ${o.n}`),Markup.inlineKeyboard([[cb("🔙 Back","home")]]))});
bot.action("my_orders",async ctx=>{await ctx.answerCbQuery();const r=await pool.query("SELECT * FROM orders WHERE user_id=$1 ORDER BY created_at DESC LIMIT 10",[ctx.from.id]);await render(ctx,box("📦 MY ORDERS",r.rows.length?r.rows.map((o:any)=>`✅ #${o.id} • ${o.product_name} x${o.quantity} • $${Number(o.total).toFixed(2)}`).join("\n"):"No orders yet."),Markup.inlineKeyboard([[cb("🔙 Back","home")]]))});
bot.action("support",async ctx=>{await ctx.answerCbQuery();await render(ctx,box("🎧 SUPPORT",`Contact support: ${config.supportUsername}`),Markup.inlineKeyboard([[cb("🔙 Back","home")]]))});
bot.action("help",async ctx=>{await ctx.answerCbQuery();const r=await pool.query("SELECT * FROM help_items WHERE active=TRUE ORDER BY title");await render(ctx,box("❓ HELP",r.rows.length?r.rows.map((x:any)=>`❓ ${x.title}\n${x.content}`).join("\n\n"):"No help articles yet."),Markup.inlineKeyboard([[cb("🔙 Back","home")]]))});
bot.action(/^buy:(.+)$/,async ctx=>{await ctx.answerCbQuery();setState(ctx.from.id,{step:"buy_qty",productId:ctx.match[1]});await render(ctx,"Send quantity:")});
bot.action("deposit",async ctx=>{await ctx.answerCbQuery();await render(ctx,box("➕ DEPOSIT FUNDS","Choose your deposit method:\n\nFast approval • Secure balance top-up ⚡"),Markup.inlineKeyboard([[cb("🟡 Binance Pay","deposit_binance")],[cb("🔙 Back to Wallet","wallet")]]))});
bot.action("deposit_binance",async ctx=>{await ctx.answerCbQuery();const uid=await getSetting("deposit_binance_uid");if(!uid){await render(ctx,box("🟡 BINANCE PAY","Deposit is temporarily unavailable.\nAdmin has not configured the Binance UID yet."),Markup.inlineKeyboard([[cb("🔙 Back","deposit")]]));return}setState(ctx.from.id,{step:"deposit_amount"});await render(ctx,box("🟡 BINANCE DEPOSIT","How much do you want to deposit?\n\nSend amount in USD, for example: 10"),Markup.inlineKeyboard([[cb("🔙 Cancel","wallet")]]))});
bot.action(/^deposit_approve:(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();const c=await pool.connect();try{await c.query("BEGIN");const d=(await c.query("SELECT * FROM deposits WHERE id=$1 FOR UPDATE",[ctx.match[1]])).rows[0];if(!d||d.status!=="pending"){await c.query("ROLLBACK");await render(ctx,"ℹ️ This deposit has already been reviewed.");return}await c.query("UPDATE deposits SET status='approved',reviewed_by=$1,reviewed_at=NOW() WHERE id=$2",[ctx.from.id,d.id]);await c.query("UPDATE users SET balance=balance+$1 WHERE id=$2",[d.amount,d.user_id]);await c.query("INSERT INTO balance_ledger(user_id,amount,reason,admin_id) VALUES($1,$2,$3,$4)",[d.user_id,d.amount,`Binance deposit #${d.id}`,ctx.from.id]);await c.query("COMMIT");await render(ctx,box("✅ DEPOSIT APPROVED",`ID: #${d.id}\nUser: ${d.user_id}\nAmount: $${Number(d.amount).toFixed(2)}\n\nBalance credited successfully 🚀`));await bot.telegram.sendMessage(d.user_id,box("✅ DEPOSIT APPROVED",`Your Binance deposit of $${Number(d.amount).toFixed(2)} has been added to your wallet.\nDeposit ID: #${d.id}`))}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}});
bot.action(/^deposit_reject:(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();const r=await pool.query("UPDATE deposits SET status='rejected',reviewed_by=$1,reviewed_at=NOW() WHERE id=$2 AND status='pending' RETURNING *",[ctx.from.id,ctx.match[1]]);if(!r.rows[0]){await render(ctx,"ℹ️ This deposit has already been reviewed.");return}const d=r.rows[0];await render(ctx,box("❌ DEPOSIT REJECTED",`ID: #${d.id}\nUser: ${d.user_id}\nAmount: $${Number(d.amount).toFixed(2)}`));await bot.telegram.sendMessage(d.user_id,box("❌ DEPOSIT REJECTED",`Your Binance deposit #${d.id} could not be verified.\nPlease contact support if you believe this is a mistake.`))});

bot.action("admin_home",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();await admin(ctx)});bot.action("admin_tools",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();await tools(ctx)});bot.action(/^admin_tool:(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();await tool(ctx,ctx.match[1])});
bot.action("admin_add_tool",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();setState(ctx.from.id,{step:"add_product_name"});await render(ctx,"Send tool name:")});
bot.action(/^field:([^:]+):(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();const field=ctx.match[1];const allowed=new Set(["price","warranty","description","note","delivery_note","delivery_template","name"]);if(!allowed.has(field))return;setState(ctx.from.id,{step:"field",field,productId:ctx.match[2],numeric:field==="price"});await render(ctx,`Send new ${field.replaceAll("_"," ")}:`)});
bot.action(/^clear:(note|delivery_note):(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();await pool.query(`UPDATE products SET ${ctx.match[1]}='' WHERE id=$1`,[ctx.match[2]]);await render(ctx,"✅ Updated.")});
bot.action(/^toggle:(stock_enabled|preorder_enabled|client_mail_activation):(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();await pool.query(`UPDATE products SET ${ctx.match[1]}=NOT ${ctx.match[1]} WHERE id=$1`,[ctx.match[2]]);await tool(ctx,ctx.match[2])});
bot.action(/^supplier:(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();await render(ctx,box("🔌 LINK SUPPLIER API","Supplier extension point is ready. Add the exact supplier API contract and credentials before live use."))});
bot.action(/^subtool_add:(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();await render(ctx,"Sub-tool framework is included; full Telegram creation wizard is the next extension point.")});
bot.action(/^subtool_manage:(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();const r=await pool.query("SELECT * FROM products WHERE parent_id=$1 ORDER BY name",[ctx.match[1]]);await render(ctx,box("🧰 SUB TOOLS",r.rows.length?r.rows.map((p:any)=>`📦 ${p.name}`).join("\n"):"No sub-tools."))});
bot.action(/^remove_tool:(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();await render(ctx,box("⚠️ REMOVE TOOL?","This removes the product and its stock."),Markup.inlineKeyboard([[cb("🗑 YES, REMOVE",`remove_tool_yes:${ctx.match[1]}`)],[cb("❌ Cancel",`admin_tool:${ctx.match[1]}`)]]))});
bot.action(/^remove_tool_yes:(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();await pool.query("DELETE FROM products WHERE id=$1",[ctx.match[1]]);await render(ctx,"✅ Tool removed.");await tools(ctx)});

bot.action("admin_manage",async ctx=>{if(Number(ctx.from.id)!==config.adminId){await ctx.answerCbQuery("Only the main owner can manage admins.",{show_alert:true});return}await ctx.answerCbQuery();const r=await pool.query("SELECT id,created_at FROM admins ORDER BY created_at");const list=[`👑 Main Owner: ${config.adminId}`,...r.rows.map((x:any,i:number)=>`🛡 Admin ${i+1}: ${x.id}`)].join("\n");await render(ctx,box("👑 ADMIN MANAGEMENT",`${list}\n\nKeep the squad trusted 🔐`),Markup.inlineKeyboard([[cb("➕ Add New Admin","admin_add")],[cb("➖ Remove Admin","admin_remove")],[cb("🔙 Back","admin_home")]]))});
bot.action("admin_add",async ctx=>{if(Number(ctx.from.id)!==config.adminId)return;await ctx.answerCbQuery();setState(ctx.from.id,{step:"admin_add"});await render(ctx,box("➕ ADD ADMIN","Send the new admin's Telegram numeric User ID."),Markup.inlineKeyboard([[cb("🔙 Cancel","admin_manage")]]))});
bot.action("admin_remove",async ctx=>{if(Number(ctx.from.id)!==config.adminId)return;await ctx.answerCbQuery();setState(ctx.from.id,{step:"admin_remove"});await render(ctx,box("➖ REMOVE ADMIN","Send the admin's Telegram numeric User ID.\nThe main owner can never be removed."),Markup.inlineKeyboard([[cb("🔙 Cancel","admin_manage")]]))});

bot.action("admin_stock",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();await render(ctx,box("📦 Stock Management","Choose an action:"),Markup.inlineKeyboard([[cb("➕ Add Stock","stock_add_pick"),cb("➖ Remove Stock","stock_remove_pick")],[cb("✅ Sold Stock","stock_sold"),cb("📦 Unsold Stock","stock_unsold")],[cb("📊 Stock Overview","stock_overview")],[cb("🔙 Back","admin_home")]]))});
bot.action("stock_add_pick",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();await picker(ctx,"stock_add","➕ ADD STOCK")});bot.action(/^stock_add:(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();setState(ctx.from.id,{step:"add_stock",productId:ctx.match[1]});await render(ctx,"Paste stock now. Each non-empty line = one item.")});
bot.action("stock_remove_pick",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();await picker(ctx,"stock_remove","➖ REMOVE STOCK")});bot.action(/^stock_remove:(.+)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();setState(ctx.from.id,{step:"remove_stock",productId:ctx.match[1]});await render(ctx,"Send quantity to remove from beginning of stock:")});
bot.action("stock_overview",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();const ps=await getProducts();const l=[];for(const p of ps){const n=await stockCount(p.id);l.push(`${n>5?"🟢":n>0?"🟡":"🔴"} ${p.name} — ${n}`)}await render(ctx,box("📊 STOCK OVERVIEW",l.join("\n")||"No products."))});
bot.action("stock_unsold",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();const r=await pool.query("SELECT product_id,COUNT(*)::int n FROM stock_items WHERE sold=FALSE GROUP BY product_id");await render(ctx,box("📦 UNSOLD STOCK",r.rows.length?r.rows.map((x:any)=>`${x.product_id}: ${x.n}`).join("\n"):"No unsold stock."))});
bot.action("stock_sold",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();const r=await pool.query("SELECT product_id,COUNT(*)::int n FROM stock_items WHERE sold=TRUE GROUP BY product_id");await render(ctx,box("✅ SOLD STOCK",r.rows.length?r.rows.map((x:any)=>`${x.product_id}: ${x.n}`).join("\n"):"No sold stock."))});

for(const [a,k] of [["admin_balance_add","add"],["admin_balance_remove","remove"],["admin_balance_check","check"]] as const){bot.action(a,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();setState(ctx.from.id,{step:"balance_user",action:k});await render(ctx,"Send Telegram User ID:")})}
bot.action("admin_track",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();setState(ctx.from.id,{step:"track_order"});await render(ctx,"Send Order ID:")});bot.action("admin_broadcast",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();setState(ctx.from.id,{step:"broadcast"});await render(ctx,"Send broadcast text:")});
bot.action("admin_coupons",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();const r=await pool.query("SELECT * FROM coupons WHERE active=TRUE ORDER BY created_at DESC");await render(ctx,box("🎟 COUPONS",r.rows.length?r.rows.map((x:any)=>`${x.code} — ${Number(x.percent)}%`).join("\n"):"No active coupons."),Markup.inlineKeyboard([[cb("➕ Create Coupon","coupon_create")],[cb("🔙 Back","admin_home")]]))});bot.action("coupon_create",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();setState(ctx.from.id,{step:"coupon_code"});await render(ctx,"Send coupon code:")});
bot.action("admin_help",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();const r=await pool.query("SELECT * FROM help_items ORDER BY title");await render(ctx,box("❓ HELP MANAGE",r.rows.length?r.rows.map((x:any)=>`• ${x.title}`).join("\n"):"No help items."),Markup.inlineKeyboard([[cb("➕ Add Help Button","help_create")],[cb("🔙 Back","admin_home")]]))});bot.action("help_create",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();setState(ctx.from.id,{step:"help_title"});await render(ctx,"Send help title:")});
bot.action("admin_payment",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();const vals:any={};for(const k of ["wallet_enabled","bep20_enabled","trc20_enabled"]){const r=await pool.query("SELECT value FROM settings WHERE key=$1",[k]);vals[k]=r.rows[0]?.value!=="false"}const binanceUid=await getSetting("deposit_binance_uid"),binanceName=await getSetting("deposit_binance_name");await render(ctx,box("💳 PAYMENT SETTINGS",`💰 Wallet: ${vals.wallet_enabled?"✅ ON":"❌ OFF"}\n💎 USDT BEP20: ${vals.bep20_enabled?"✅ ON":"❌ OFF"}\n💎 USDT TRC20: ${vals.trc20_enabled?"✅ ON":"❌ OFF"}\n\n🟡 Binance Deposit: ${binanceUid?"✅ READY":"❌ NOT SET"}\n👤 Binance Name: ${binanceName||"Not set"}`),Markup.inlineKeyboard([[cb(`💰 Wallet: ${vals.wallet_enabled?"✅":"❌"}`,"pay:wallet_enabled")],[cb(`💎 BEP20: ${vals.bep20_enabled?"✅":"❌"}`,"pay:bep20_enabled"),cb(`💎 TRC20: ${vals.trc20_enabled?"✅":"❌"}`,"pay:trc20_enabled")],[cb("🟡 Set Binance UID","set_binance_uid"),cb("👤 Set Binance Name","set_binance_name")],[cb("🔙 Back","admin_home")]]))});
bot.action("set_binance_uid",async ctx=>{if(Number(ctx.from.id)!==config.adminId)return;await ctx.answerCbQuery();setState(ctx.from.id,{step:"binance_uid"});await render(ctx,box("🟡 BINANCE UID","Send the Binance Pay UID users should pay."),Markup.inlineKeyboard([[cb("🔙 Cancel","admin_payment")]]))});
bot.action("set_binance_name",async ctx=>{if(Number(ctx.from.id)!==config.adminId)return;await ctx.answerCbQuery();setState(ctx.from.id,{step:"binance_name"});await render(ctx,box("👤 BINANCE NAME","Send the receiver/account name shown to users."),Markup.inlineKeyboard([[cb("🔙 Cancel","admin_payment")]]))});
bot.action(/^pay:(wallet_enabled|bep20_enabled|trc20_enabled)$/,async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery("Updated ✅");const k=ctx.match[1];const r=await pool.query("SELECT value FROM settings WHERE key=$1",[k]);const v=r.rows[0]?.value==="false"?"true":"false";await pool.query("INSERT INTO settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value",[k,v]);await render(ctx,box("✅ PAYMENT UPDATED",`${k.replaceAll("_"," ").toUpperCase()} is now ${v==="true"?"ON 🟢":"OFF 🔴"}`),Markup.inlineKeyboard([[cb("🔙 Payment Settings","admin_payment")]]))});
bot.action("admin_dashboard",async ctx=>{if(!await hasAdminAccess(ctx))return;await ctx.answerCbQuery();const [u,p,o,s,st]=await Promise.all([pool.query("SELECT COUNT(*)::int n FROM users"),pool.query("SELECT COUNT(*)::int n FROM products"),pool.query("SELECT COUNT(*)::int n FROM orders"),pool.query("SELECT COALESCE(SUM(total),0) t FROM orders WHERE created_at::date=CURRENT_DATE"),pool.query("SELECT COUNT(*)::int n FROM stock_items WHERE sold=FALSE")]);await render(ctx,box("📊 DASHBOARD",`👥 Users: ${u.rows[0].n}\n📦 Products: ${p.rows[0].n}\n🧾 Orders: ${o.rows[0].n}\n💰 Sales Today: $${Number(s.rows[0].t).toFixed(2)}\n📊 Unsold Stock: ${st.rows[0].n}`))});

bot.on(message("text"),async ctx=>{await ensureUser(ctx.from.id,ctx.from.username,ctx.from.first_name);const uid=ctx.from.id,s=getState(uid),text=ctx.message.text.trim();if(!s)return;
if(s.step==="buy_qty"){const q=Number(text);if(!Number.isInteger(q)||q<1)return void render(ctx,"❌ Invalid quantity.");const c=await pool.connect();try{await c.query("BEGIN");const p=(await c.query("SELECT * FROM products WHERE id=$1 FOR UPDATE",[s.productId])).rows[0];if(!p)throw new Error("Product not found.");const stock=await c.query("SELECT * FROM stock_items WHERE product_id=$1 AND sold=FALSE ORDER BY id FOR UPDATE LIMIT $2",[p.id,q]);if(stock.rows.length<q)throw new Error("Insufficient stock.");const u=(await c.query("SELECT * FROM users WHERE id=$1 FOR UPDATE",[uid])).rows[0],total=Number(p.price)*q;if(Number(u?.balance||0)<total)throw new Error("Insufficient wallet balance.");const oid=id8(),vals=stock.rows.map((x:any)=>x.value);await c.query("UPDATE users SET balance=balance-$1 WHERE id=$2",[total,uid]);for(const x of stock.rows)await c.query("UPDATE stock_items SET sold=TRUE,sold_order_id=$1 WHERE id=$2",[oid,x.id]);await c.query("INSERT INTO orders(id,user_id,product_id,product_name,quantity,unit_price,total,delivery) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[oid,uid,p.id,p.name,q,p.price,total,vals.join("\n")]);await c.query("COMMIT");clearState(uid);await render(ctx,box("✅ ORDER COMPLETED",`📦 Product: ${p.name}\n🔢 Qty: ${q}\n🆔 Order ID: #${oid}\n💰 Paid: $${total.toFixed(2)}\n\n━━━━━━━━ DELIVERY ━━━━━━━━\n\n${vals.map((v:string,i:number)=>`${i+1}.\n${v}`).join("\n\n")}\n\nThank you for shopping with STORE DN CAR.`))}catch(e:any){await c.query("ROLLBACK");await render(ctx,`❌ ${e.message}`)}finally{c.release()}return}
if(s.step==="deposit_amount"){const amount=Number(text);if(!Number.isFinite(amount)||amount<=0)return void render(ctx,"❌ Send a valid deposit amount greater than 0.");const binanceUid=await getSetting("deposit_binance_uid"),binanceName=await getSetting("deposit_binance_name");if(!binanceUid){clearState(uid);return void render(ctx,"❌ Binance deposit is temporarily unavailable.")}setState(uid,{step:"deposit_txid",amount});return void render(ctx,box("🟡 COMPLETE BINANCE PAYMENT",`Amount: $${amount.toFixed(2)}\nBinance UID: ${binanceUid}\nReceiver: ${binanceName||"STORE DN CAR"}\n\nAfter payment, send the Binance Transaction ID (TXID).\n⚠️ Never send your password or OTP.`))}
if(s.step==="deposit_txid"){if(text.length<4||text.length>160)return void render(ctx,"❌ Send a valid Binance Transaction ID (TXID).");const duplicate=await pool.query("SELECT 1 FROM deposits WHERE method='binance' AND LOWER(txid)=LOWER($1)",[text]);if(duplicate.rowCount)return void render(ctx,"❌ This TXID has already been submitted.");const depositId=id8();await pool.query("INSERT INTO deposits(id,user_id,amount,method,txid) VALUES($1,$2,$3,'binance',$4)",[depositId,uid,s.amount,text]);clearState(uid);await render(ctx,box("⏳ DEPOSIT SUBMITTED",`Deposit ID: #${depositId}\nAmount: $${s.amount.toFixed(2)}\nMethod: Binance Pay\n\nAdmin verification is pending. Your wallet will update after approval.`),Markup.inlineKeyboard([[cb("💰 Back to Wallet","wallet")]]));const notice=box("🟡 NEW BINANCE DEPOSIT",`Deposit ID: #${depositId}\nUser: ${uid}\nUsername: @${ctx.from.username||"N/A"}\nAmount: $${s.amount.toFixed(2)}\nTXID: ${text}`),buttons=Markup.inlineKeyboard([[cb("✅ Approve",`deposit_approve:${depositId}`),cb("❌ Reject",`deposit_reject:${depositId}`)]]);for(const adminId of await adminIds()){try{await bot.telegram.sendMessage(adminId,notice,buttons)}catch{}}return}
if(!await hasAdminAccess(ctx))return;
if(s.step==="binance_uid"){if(uid!==config.adminId)return;if(!/^\d{4,30}$/.test(text))return void render(ctx,"❌ Send a valid numeric Binance UID.");await setSetting("deposit_binance_uid",text);clearState(uid);return void render(ctx,box("✅ BINANCE UID SAVED",`Deposit receiver UID: ${text}`),Markup.inlineKeyboard([[cb("💳 Payment Settings","admin_payment")]]))}
if(s.step==="binance_name"){if(uid!==config.adminId)return;if(text.length<2||text.length>80)return void render(ctx,"❌ Send a valid receiver name.");await setSetting("deposit_binance_name",text);clearState(uid);return void render(ctx,box("✅ BINANCE NAME SAVED",`Receiver: ${text}`),Markup.inlineKeyboard([[cb("💳 Payment Settings","admin_payment")]]))}
if(s.step==="admin_add"){if(uid!==config.adminId)return;const id=Number(text);if(!Number.isSafeInteger(id)||id<=0)return void render(ctx,"❌ Send a valid numeric Telegram User ID.");if(id===config.adminId){clearState(uid);return void render(ctx,"👑 That ID is already the main owner.")}await pool.query("INSERT INTO admins(id,added_by) VALUES($1,$2) ON CONFLICT(id) DO NOTHING",[id,uid]);clearState(uid);return void render(ctx,box("✅ NEW ADMIN ADDED",`User ${id} is now part of the boss squad 😎`),Markup.inlineKeyboard([[cb("👑 Admin Management","admin_manage")]]))}
if(s.step==="admin_remove"){if(uid!==config.adminId)return;const id=Number(text);if(!Number.isSafeInteger(id)||id<=0)return void render(ctx,"❌ Send a valid numeric Telegram User ID.");if(id===config.adminId){clearState(uid);return void render(ctx,"❌ Main owner cannot be removed.")}const removed=await pool.query("DELETE FROM admins WHERE id=$1 RETURNING id",[id]);clearState(uid);return void render(ctx,box(removed.rowCount?"✅ ADMIN REMOVED":"ℹ️ ADMIN NOT FOUND",removed.rowCount?`User ${id} no longer has admin access.`:`User ${id} was not in the admin list.`),Markup.inlineKeyboard([[cb("👑 Admin Management","admin_manage")]]))}
if(s.step==="add_product_name"){setState(uid,{step:"add_product_price",name:text});return void render(ctx,"Send price:")}if(s.step==="add_product_price"){const p=Number(text);if(!Number.isFinite(p)||p<0)return void render(ctx,"❌ Invalid price.");setState(uid,{step:"add_product_warranty",name:s.name,price:p});return void render(ctx,"Send warranty:")}if(s.step==="add_product_warranty"){setState(uid,{step:"add_product_desc",name:s.name,price:s.price,warranty:text});return void render(ctx,"Send description:")}if(s.step==="add_product_desc"){const id=id8();await pool.query("INSERT INTO products(id,name,price,warranty,description) VALUES($1,$2,$3,$4,$5)",[id,s.name,s.price,s.warranty,text]);clearState(uid);return void render(ctx,`✅ Tool created.\nID: ${id}`)}if(s.step==="field"){const v=s.numeric?Number(text):text;if(s.numeric&&(!Number.isFinite(v)||Number(v)<0))return void render(ctx,"❌ Invalid number.");await pool.query(`UPDATE products SET ${s.field}=$1 WHERE id=$2`,[v,s.productId]);clearState(uid);return void render(ctx,"✅ Updated.")}
if(s.step==="add_stock"){const items=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let a=0,d=0;for(const x of items){const r=await pool.query("INSERT INTO stock_items(product_id,value) VALUES($1,$2) ON CONFLICT(product_id,value) DO NOTHING RETURNING id",[s.productId,x]);r.rowCount?a++:d++}clearState(uid);return void render(ctx,`✅ STOCK IMPORT COMPLETE\n\n📥 Received: ${items.length}\n✅ Added: ${a}\n♻️ Duplicates: ${d}\n📦 Total Stock: ${await stockCount(s.productId)}`)}
if(s.step==="remove_stock"){const q=Number(text);if(!Number.isInteger(q)||q<1)return void render(ctx,"❌ Invalid quantity.");const p=await getProduct(s.productId),r=await pool.query("SELECT * FROM stock_items WHERE product_id=$1 AND sold=FALSE ORDER BY id LIMIT $2",[s.productId,q]);if(!r.rows.length){clearState(uid);return void render(ctx,"No unsold stock.")}await pool.query("DELETE FROM stock_items WHERE id=ANY($1::bigint[])",[r.rows.map((x:any)=>x.id)]);const body=`STORE DN CAR\nREMOVED STOCK BACKUP\n\nProduct:\n${p?.name||s.productId}\n\nRemoved:\n${r.rows.length}\n\nDate:\n${new Date().toISOString()}\n\n--------------------------------\n\n${r.rows.map((x:any,i:number)=>`${i+1}. ${x.value}`).join("\n")}`;clearState(uid);await ctx.replyWithDocument({source:Buffer.from(body),filename:`removed_${(p?.name||"stock").replace(/[^a-z0-9]+/gi,"_")}_${Date.now()}.txt`});return}
if(s.step==="balance_user"){const id=Number(text);if(!Number.isInteger(id))return void render(ctx,"❌ Invalid user ID.");const u=await getUser(id);if(!u)return void render(ctx,"❌ User not found.");if(s.action==="check"){clearState(uid);const o=(await pool.query("SELECT COUNT(*)::int n,COALESCE(SUM(total),0) t FROM orders WHERE user_id=$1",[id])).rows[0];return void render(ctx,box("💰 BALANCE CHECK",`🆔 User ID: ${id}\n💰 Current Balance: $${Number(u.balance).toFixed(2)}\n📦 Total Orders: ${o.n}\n💸 Total Spent: $${Number(o.t).toFixed(2)}`))}setState(uid,{step:"balance_amount",action:s.action,userId:id});return void render(ctx,"Send amount:")}
if(s.step==="balance_amount"){const a=Number(text);if(!Number.isFinite(a)||a<=0)return void render(ctx,"❌ Invalid amount.");const u=await getUser(s.userId);if(s.action==="remove"&&Number(u.balance)<a)return void render(ctx,"❌ Insufficient user balance.");const v=s.action==="add"?a:-a;await pool.query("UPDATE users SET balance=balance+$1 WHERE id=$2",[v,s.userId]);await pool.query("INSERT INTO balance_ledger(user_id,amount,reason,admin_id) VALUES($1,$2,$3,$4)",[s.userId,v,`Admin ${s.action} balance`,config.adminId]);clearState(uid);return void render(ctx,"✅ Balance updated.")}
if(s.step==="track_order"){const id=text.replace(/^#/,"").toUpperCase(),r=await pool.query("SELECT * FROM orders WHERE id=$1",[id]);clearState(uid);if(!r.rows[0])return void render(ctx,"❌ Order not found.");const o=r.rows[0];await render(ctx,box("🔎 ORDER DETAILS",`🆔 Order: #${o.id}\n🆔 User ID: ${o.user_id}\n📦 Product: ${o.product_name}\n🔢 Quantity: ${o.quantity}\n💰 Unit Price: $${Number(o.unit_price).toFixed(2)}\n💵 Total: $${Number(o.total).toFixed(2)}\n✅ Status: ${o.status}\n📅 Date: ${o.created_at}`));for(const c of String(o.delivery||"").match(/[\s\S]{1,3000}/g)||[])await render(ctx,`📦 Delivery Data\n\n${c}`);return}
if(s.step==="broadcast"){clearState(uid);const us=await pool.query("SELECT id FROM users");let ok=0,bad=0;for(const u of us.rows){try{await bot.telegram.sendMessage(u.id,text);ok++}catch{bad++}}return void render(ctx,`📢 BROADCAST COMPLETE\n\nSent: ${ok}\nFailed: ${bad}\nTotal: ${us.rows.length}`)}if(s.step==="coupon_code"){setState(uid,{step:"coupon_percent",code:text.toUpperCase()});return void render(ctx,"Send discount percent:")}if(s.step==="coupon_percent"){const p=Number(text);if(!Number.isFinite(p)||p<=0||p>100)return void render(ctx,"❌ Invalid percent.");await pool.query("INSERT INTO coupons(code,percent) VALUES($1,$2) ON CONFLICT(code) DO UPDATE SET percent=EXCLUDED.percent,active=TRUE",[s.code,p]);clearState(uid);return void render(ctx,"✅ Coupon saved.")}if(s.step==="help_title"){setState(uid,{step:"help_content",id:id8(),title:text});return void render(ctx,"Send help content:")}if(s.step==="help_content"){await pool.query("INSERT INTO help_items(id,title,content) VALUES($1,$2,$3)",[s.id,s.title,text]);clearState(uid);return void render(ctx,"✅ Help item added.")}});
bot.catch(err=>console.error(err));await initDb();await bot.launch();console.log("STORE DN CAR bot started");process.once("SIGINT",()=>bot.stop("SIGINT"));process.once("SIGTERM",()=>bot.stop("SIGTERM"));
